# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBzBjsGJJiN36BDWWQ48SEdMQpXbK43D
"""

attributes = ['Sky', 'Temp', 'Humidity', 'Wind', 'Water', 'Forecast']

dataset = [
    ['Cloudy',   'Cold', 'High',   'Strong', 'Warm', 'Change', 'Yes'],
    ['Sunny',    'Warm', 'Normal', 'Strong', 'Warm', 'Same',   'Yes'],
    ['Sunny',    'Warm', 'High',   'Strong', 'Warm', 'Same',   'Yes'],
    ['Cloudy',   'Cold', 'High',   'Strong', 'Warm', 'Change', 'No'],
    ['Sunny',    'Warm', 'High',   'Strong', 'Cool', 'Change', 'Yes'],
    ['Rain',     'Mild', 'High',   'Weak',   'Cool', 'Change', 'No'],
    ['Rain',     'Cool', 'Normal', 'Weak',   'Cool', 'Same',   'No'],
    ['Overcast', 'Cool', 'Normal', 'Strong', 'Warm', 'Same',   'Yes'],
]

num_attributes = len(attributes)

print('Attributes   :', attributes)
print('\nTraining Dataset:')
for row in dataset:
    print(' ', row)

hypothesis = ['0'] * num_attributes
print('\nInitial Hypothesis:', hypothesis)

print('\nHypothesis updates (positive examples only):')
for i, instance in enumerate(dataset):
    target = instance[-1]

    if target == 'Yes':
        for j in range(num_attributes):
            if hypothesis[j] == '0':
                hypothesis[j] = instance[j]
            elif hypothesis[j] != instance[j]:
                hypothesis[j] = '?'

        print(f'  Example {i+1} {instance[:-1]} --> Hypothesis: {hypothesis}')

print('\nFinal Most-Specific Consistent Hypothesis:')
print(hypothesis)

data = [
    ['Cloudy',   'Cold', 'High',   'Strong', 'Warm', 'Change', 'Yes'],
    ['Sunny',    'Warm', 'Normal', 'Strong', 'Warm', 'Same',   'Yes'],
    ['Sunny',    'Warm', 'High',   'Strong', 'Warm', 'Same',   'Yes'],
    ['Cloudy',   'Cold', 'High',   'Strong', 'Warm', 'Change', 'No'],
    ['Sunny',    'Warm', 'High',   'Strong', 'Cool', 'Change', 'Yes'],
    ['Rain',     'Mild', 'High',   'Weak',   'Cool', 'Change', 'No'],
    ['Rain',     'Cool', 'Normal', 'Weak',   'Cool', 'Same',   'No'],
    ['Overcast', 'Cool', 'Normal', 'Strong', 'Warm', 'Same',   'Yes'],
]

concepts = [row[:-1] for row in data]
target   = [row[-1]  for row in data]

def learn(concepts, target):
    specific_h = concepts[0][:]
    general_h  = [['?' for i in range(len(specific_h))] for i in range(len(specific_h))]

    print("Initialization of specific_h and general_h")
    print(specific_h)
    print(general_h)

    for i, h in enumerate(concepts):
        if target[i] == 'Yes':
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    specific_h[x]   = '?'
                    general_h[x][x] = '?'

        if target[i] == 'No':
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    general_h[x][x] = specific_h[x]
                else:
                    general_h[x][x] = '?'

        print("\nStep", i + 1, "of Candidate Elimination Algorithm")
        print("Specific_h:", specific_h)
        print("General_h :", general_h)

    indices = [i for i, val in enumerate(general_h) if val == ['?', '?', '?', '?', '?', '?']]
    for i in indices:
        general_h.remove(['?', '?', '?', '?', '?', '?'])

    return specific_h, general_h

s_final, g_final = learn(concepts, target)

print("\nFinal Specific_h:", s_final, sep="\n")
print("Final General_h:",  g_final, sep="\n")

import numpy as np

dataset = [
    ['Sunny',    'Hot',  'High',   'Weak',   'No'],
    ['Sunny',    'Hot',  'High',   'Strong', 'No'],
    ['Overcast', 'Hot',  'High',   'Weak',   'Yes'],
    ['Rain',     'Mild', 'High',   'Weak',   'Yes'],
    ['Rain',     'Cool', 'Normal', 'Weak',   'Yes'],
    ['Rain',     'Cool', 'Normal', 'Strong', 'No'],
    ['Overcast', 'Cool', 'Normal', 'Strong', 'Yes'],
    ['Sunny',    'Mild', 'High',   'Weak',   'No'],
    ['Sunny',    'Cool', 'Normal', 'Weak',   'Yes'],
    ['Rain',     'Mild', 'Normal', 'Weak',   'Yes'],
    ['Sunny',    'Mild', 'Normal', 'Strong', 'Yes'],
    ['Overcast', 'Mild', 'High',   'Strong', 'Yes'],
    ['Overcast', 'Hot',  'Normal', 'Weak',   'Yes'],
    ['Rain',     'Mild', 'High',   'Strong', 'No'],
]

columns = ['outlook', 'temperature', 'humidity', 'wind', 'class']

import pandas as pd
data = pd.DataFrame(dataset, columns=columns)

def entropy(target_col):
    elements, counts = np.unique(target_col, return_counts=True)
    return np.sum([(-counts[i] / np.sum(counts)) * np.log2(counts[i] / np.sum(counts)) for i in range(len(elements))])

def InfoGain(data, split_attribute_name, target_name="class"):
    total_entropy = entropy(data[target_name])
    vals, counts = np.unique(data[split_attribute_name], return_counts=True)
    weighted_entropy = np.sum([(counts[i] / np.sum(counts)) * entropy(data.where(data[split_attribute_name] == vals[i]).dropna()[target_name]) for i in range(len(vals))])
    return total_entropy - weighted_entropy

def ID3(data, originaldata, features, target_attribute_name="class", parent_node_class=None):
    if len(np.unique(data[target_attribute_name])) <= 1:
        return np.unique(data[target_attribute_name])[0]
    elif len(data) == 0:
        return np.unique(originaldata[target_attribute_name])[np.argmax(np.unique(originaldata[target_attribute_name], return_counts=True)[1])]
    elif len(features) == 0:
        return parent_node_class
    else:
        parent_node_class = np.unique(data[target_attribute_name])[np.argmax(np.unique(data[target_attribute_name], return_counts=True)[1])]
        item_values = [InfoGain(data, feature, target_attribute_name) for feature in features]
        best_feature = features[np.argmax(item_values)]
        tree = {best_feature: {}}
        features = [i for i in features if i != best_feature]
        for value in np.unique(data[best_feature]):
            sub_data = data.where(data[best_feature] == value).dropna()
            subtree = ID3(sub_data, originaldata, features, target_attribute_name, parent_node_class)
            tree[best_feature][value] = subtree
        return tree

tree = ID3(data, data, list(data.columns[:-1]))
print("\nDisplay Tree\n", tree)

import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

X = X / np.amax(X, axis=0)
y = y / 100

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

epoch = 7000
lr = 0.1
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1

wh   = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh   = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

for i in range(epoch):
    hinp       = np.dot(X, wh) + bh
    hlayer_act = sigmoid(hinp)
    outinp     = np.dot(hlayer_act, wout) + bout
    output     = sigmoid(outinp)

    EO          = y - output
    outgrad     = derivatives_sigmoid(output)
    d_output    = EO * outgrad

    EH            = d_output.dot(wout.T)
    hiddengrad    = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad

    wout += hlayer_act.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr
    wh   += X.T.dot(d_hiddenlayer) * lr
    bh   += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr

print("Input:\n", X)
print("Actual Output:\n", y)
print("Predicted Output:\n", output)

import random
import math

dataset = [
    [6,148,72,35,0,33.6,0.627,50,1],[1,85,66,29,0,26.6,0.351,31,0],[8,183,64,0,0,23.3,0.672,32,1],
    [1,89,66,23,94,28.1,0.167,21,0],[0,137,40,35,168,43.1,2.288,33,1],[5,116,74,0,0,25.6,0.201,30,0],
    [3,78,50,32,88,31.0,0.248,26,1],[10,115,0,0,0,35.3,0.134,29,0],[2,197,70,45,543,30.5,0.158,53,1],
    [8,125,96,0,0,0.0,0.232,54,1],[4,110,92,0,0,37.6,0.191,30,0],[10,168,74,0,0,38.0,0.537,34,1],
    [10,139,80,0,0,27.1,1.441,57,0],[1,189,60,23,846,30.1,0.398,59,1],[5,166,72,19,175,25.8,0.587,51,1],
    [7,100,0,0,0,30.0,0.484,32,1],[0,118,84,47,230,45.8,0.551,31,1],[7,107,74,0,0,29.6,0.254,31,1],
    [1,103,30,38,83,43.3,0.183,33,0],[1,115,70,30,96,34.6,0.529,32,1],[3,126,88,41,235,39.3,0.704,27,0],
    [8,99,84,0,0,35.4,0.388,50,0],[7,196,90,0,0,39.8,0.451,41,1],[9,119,80,35,0,29.0,0.263,29,1],
    [11,143,94,33,146,36.6,0.254,51,1],[10,125,70,26,115,31.1,0.205,41,1],[7,147,76,0,0,39.4,0.257,43,1],
    [1,97,66,15,140,23.2,0.487,22,0],[13,145,82,19,110,22.2,0.245,57,0],[5,117,92,0,0,34.1,0.337,38,0],
    [5,109,75,26,0,36.0,0.546,60,0],[3,158,76,36,245,31.6,0.851,28,1],[3,88,58,11,54,24.8,0.267,22,0],
    [6,92,92,0,0,19.9,0.188,28,0],[10,122,78,31,0,27.6,0.512,45,0],[4,103,60,33,192,24.0,0.966,33,0],
    [11,138,76,0,0,33.2,0.420,35,0],[9,102,76,37,0,32.9,0.665,46,1],[2,90,68,42,0,38.2,0.503,27,1],
    [4,111,72,47,207,37.1,1.390,56,1],[3,180,64,25,70,34.0,0.271,26,0],[7,133,84,0,0,40.2,0.696,37,0],
    [7,106,92,18,0,22.7,0.235,48,0],[9,171,110,24,240,45.4,0.721,54,1],[7,159,64,0,0,27.4,0.294,40,0],
    [0,180,66,39,0,42.0,1.893,25,1],[1,146,56,0,0,29.7,0.564,29,0],[2,71,70,27,0,28.0,0.586,22,0],
    [7,103,66,32,0,39.1,0.344,31,1],[7,105,0,0,0,0.0,0.305,24,0],[1,103,80,11,82,19.4,0.491,22,0],
]

def splitDataset(dataset, splitRatio):
    trainSize = int(len(dataset) * splitRatio)
    trainSet  = []
    copy      = list(dataset)
    while len(trainSet) < trainSize:
        index = random.randrange(len(copy))
        trainSet.append(copy.pop(index))
    return [trainSet, copy]

def separateByClass(dataset):
    separated = {}
    for vector in dataset:
        label = vector[-1]
        if label not in separated:
            separated[label] = []
        separated[label].append(vector)
    return separated

def mean(numbers):
    return sum(numbers) / float(len(numbers))

def stdev(numbers):
    avg = mean(numbers)
    variance = sum([pow(x - avg, 2) for x in numbers]) / float(len(numbers) - 1)
    return math.sqrt(variance)

def summarize(dataset):
    summaries = [(mean(attr), stdev(attr)) for attr in zip(*dataset)]
    del summaries[-1]
    return summaries

def summarizeByClass(dataset):
    separated = separateByClass(dataset)
    summaries = {}
    for classValue, instances in separated.items():
        summaries[classValue] = summarize(instances)
    return summaries

def calculateProbability(x, mean, stdev):
    if stdev == 0:
        return 1.0 if x == mean else 0.0
    exponent = math.exp(-(math.pow(x - mean, 2) / (2 * math.pow(stdev, 2))))
    return (1 / (math.sqrt(2 * math.pi) * stdev)) * exponent

def calculateClassProbabilities(summaries, inputVector):
    probabilities = {}
    for classValue, classSummaries in summaries.items():
        probabilities[classValue] = 1
        for i in range(len(classSummaries)):
            m, s = classSummaries[i]
            probabilities[classValue] *= calculateProbability(inputVector[i], m, s)
    return probabilities

def predict(summaries, inputVector):
    probabilities = calculateClassProbabilities(summaries, inputVector)
    bestLabel, bestProb = None, -1
    for classValue, probability in probabilities.items():
        if bestLabel is None or probability > bestProb:
            bestProb  = probability
            bestLabel = classValue
    return bestLabel

def getPredictions(summaries, testSet):
    return [predict(summaries, row) for row in testSet]

def getAccuracy(testSet, predictions):
    correct = sum(1 for i in range(len(testSet)) if testSet[i][-1] == predictions[i])
    return (correct / float(len(testSet))) * 100.0

splitRatio = 0.67
trainingSet, testSet = splitDataset(dataset, splitRatio)
print('Split {0} rows into train={1} and test={2} rows'.format(len(dataset), len(trainingSet), len(testSet)))

summaries   = summarizeByClass(trainingSet)
predictions = getPredictions(summaries, testSet)
accuracy    = getAccuracy(testSet, predictions)
print('Accuracy: {0}%'.format(accuracy))

import pandas as pd
import os

print("Files in current directory:", os.listdir())
msg=pd.read_csv('sample_data/naivetext1.csv',names=['message','label'])
print('The dimensions of the dataset',msg.shape)
msg['labelnum']=msg.label.map({'pos':1,'neg':0})
X=msg.message
y=msg.labelnum
print(X)
print(y)
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y)
print(xtest.shape)
print(xtrain.shape)
print(ytest.shape)
print(ytrain.shape)
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
xtrain_dtm = count_vect.fit_transform(xtrain)
xtest_dtm=count_vect.transform(xtest)
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(xtrain_dtm,ytrain)
predicted = clf.predict(xtest_dtm)
from sklearn import metrics
print('Accuracy metrics')
print('Accuracy of the classifer is',metrics.accuracy_score(ytest,predicted))
print('Confusion matrix')
print(metrics.confusion_matrix(ytest,predicted))
print('Recall and Precison ')
print(metrics.recall_score(ytest,predicted))
print(metrics.precision_score(ytest,predicted))

import pandas as pd
import os

# Create sample data for the Naive Bayes example
data = {
    'message': [
        'I love this movie', 'This is a great book', 'What a fantastic day',
        'I hate this traffic', 'The weather is terrible', 'Worst experience ever',
        'Happy to be here', 'Feeling good today', 'So much fun',
        'This is awful', 'Absolutely brilliant', 'I am so sad'
    ],
    'label': [
        'pos', 'pos', 'pos',
        'neg', 'neg', 'neg',
        'pos', 'pos', 'pos',
        'neg', 'pos', 'neg'
    ]
}

sample_df = pd.DataFrame(data)

# Define the path to save the CSV file
csv_path = 'sample_data/naivetext1.csv'

# Save the DataFrame to a CSV file in the sample_data directory
sample_df.to_csv(csv_path, index=False, header=False)

print(f"Sample 'naivetext1.csv' created at: {csv_path}")
print("Content of the created file (first 5 rows):")
print(sample_df.head())

"""Now that the sample CSV file has been created, you can try running your Naive Bayes classification code again."""

!pip install pgmpy

"""Now that the sample `kmeansdata.csv` file has been created, you can try running the K-Means and EM clustering cell (`VUXM9W6bWoPP`) again."""

import pandas as pd

# Create dataset
data = {
    'Distance_Feature': [71.24,52.53,64.54,55.69,54.58,41.91,58.64,52.02,31.25,44.31,
                         49.35,58.07,44.22,55.73,46.63,52.97,46.25,51.55,57.05,58.45,
                         43.42,55.68,55.15],
    'Speeding_Feature': [28,25,27,22,25,10,20,8,34,19,
                         40,45,22,19,43,32,35,27,26,30,
                         23,37,18]
}

df = pd.DataFrame(data)

# Save as CSV file
df.to_csv("kmeansdata.csv", index=False)

print("Dataset created successfully!")

import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.mixture import GaussianMixture
import pandas as pd

# Load dataset
X = pd.read_csv("kmeansdata.csv")

# Extract features
x1 = X['Distance_Feature'].values
x2 = X['Speeding_Feature'].values

# Convert into 2D array
X = np.array(list(zip(x1, x2))).reshape(len(x1), 2)

# Plot original data
plt.figure()
plt.xlim([0, 100])
plt.ylim([0, 50])
plt.title('Dataset')
plt.scatter(x1, x2)
plt.show()

# ================= EM Algorithm =================
gmm = GaussianMixture(n_components=3)
gmm.fit(X)

# FIXED LINE
em_predictions = gmm.predict(X)

print("\nEM predictions")
print(em_predictions)

print("\nMean:")
print(gmm.means_)

print("\nCovariances:")
print(gmm.covariances_)

# Plot EM result
plt.figure()
plt.title('Expectation Maximization')
plt.scatter(X[:, 0], X[:, 1], c=em_predictions, s=50)
plt.show()

# ================= KMeans =================
kmeans = KMeans(n_clusters=3, random_state=0)
kmeans.fit(X)

print("\nKMeans Centers:")
print(kmeans.cluster_centers_)

print("\nKMeans Labels:")
print(kmeans.labels_)

# Plot KMeans result
plt.figure()
plt.title('KMeans')
plt.scatter(X[:, 0], X[:, 1], c=kmeans.labels_, cmap='rainbow')
plt.scatter(kmeans.cluster_centers_[:, 0],
            kmeans.cluster_centers_[:, 1],
            color='black')
plt.show()

from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix is:\n", cm)

print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("correct prediction =", acc)
print("wrong prediction =", 1 - acc)

import numpy as np
import matplotlib.pyplot as plt

def local_regression(x0, X, Y, tau):
    X_b = np.c_[np.ones(len(X)), X]
    x0_b = np.array([1, x0])

    weights = np.exp(-np.sum((X_b - x0_b) ** 2, axis=1) / (2 * tau**2))
    W = np.diag(weights)

    beta = np.linalg.pinv(X_b.T @ W @ X_b) @ (X_b.T @ W @ Y)

    return x0_b @ beta

n = 100

X = np.linspace(-3, 3, n)
Y = np.log(np.abs(X**2 - 1) + 0.5)

X = X + np.random.normal(scale=0.1, size=n)

domain = np.linspace(-3, 3, 200)

def plot_lwr(tau):
    predictions = np.array([local_regression(x0, X, Y, tau) for x0 in domain])

    plt.scatter(X, Y, color='blue', alpha=0.4)
    plt.plot(domain, predictions, color='red')
    plt.title("tau = " + str(tau))
    plt.show()

plot_lwr(1)
plot_lwr(0.1)

"""Once the installation is complete, please re-run the previous cell (`4bS5C4fHSQ1m`) to execute the program."""